huynhtanduy nop bt buoi 6
itmc-ptit/itmc-cpp-class-2024 pull request #112
Opened 2024-11-15 13:23 UTC by TDuyHuynh

2024-11-17 11:14 UTC, MatthewLK13 commented on N24DCCN114/buoi6/baitap1.cpp
> +    double tb=tong/n;
tổng/n đã là 1 số nguyên, em cần phải dùng ép kiểu.

2024-11-17 11:30 UTC, MatthewLK13 requested changes

2024-11-17 11:30 UTC, MatthewLK13 commented on N24DCCN114/buoi6/baitap5.cpp
ổn, em nên tham khảo dùng thêm vector thử xem

2024-11-17 11:30 UTC, MatthewLK13 commented on N24DCCN114/buoi6/baitap6.cpp
chèn ở đây là thêm 13 vào sau số lẻ, chứ k phải thay thế số lẻ cuối cùng bằng số 13, em thử lại xem.

2024-11-24 08:56 UTC, MatthewLK13 approved these changes

2024-11-25 07:18 UTC, phungxuangiap approved these changes

2024-11-25 07:18 UTC, merged