htrang nop bt buoi 6
itmc-ptit/itmc-cpp-class-2024 pull request #117
Opened 2024-11-16 16:20 UTC by KRL0v0

2024-11-17 09:32 UTC, MatthewLK13 requested changes

2024-11-17 09:32 UTC, MatthewLK13 commented on bt2.cpp
> +    for (int i=0;i<=n;i++){
ở vòng 11, i < n thui e, vì chỉ số : 0 -> n - 1

2024-11-17 11:35 UTC, MatthewLK13 requested changes
ráng bài 7 nữa e

2024-11-17 15:07 UTC, MatthewLK13 approved these changes

2024-11-25 07:29 UTC, phungxuangiap approved these changes

2024-11-25 07:30 UTC, merged