nop bai tap buoi 4
itmc-ptit/itmc-cpp-class-2024 pull request #78
Opened 2024-11-10 06:39 UTC by yunttan

2024-11-10 10:40 UTC, thiennk581 requested changes

2024-11-10 10:40 UTC, thiennk581 commented on N24DCCN162/bai_9.cpp
> +    }else if(d<0){
d có 3 trường hợp là (d > 0), (d == 0), (d < 0). Đã if else if else để xét 2 trường hợp (d == 0) và (d  > 0) rồi nên chỉ còn lại trường hợp (d < 0), else cout << "vo nghiem" luôn không cần phải if nữa.

2024-11-10 10:40 UTC, thiennk581 commented on N24DCCN162/bai_9.cpp
> +    if (a!=0){
a == 0 thì phương trình bậc 2  (ax^2 + bx + c = 0) sẽ trở thành phương trình bậc 1 (bx + c = 0). Thiếu trường hợp này

2024-11-10 18:23 UTC, yunttan commented on N24DCCN162/bai_1.cpp
> +        if(islower(c)){
dạ điều kiện là phải là các kí tự chữ thường từ 97 đến 122 trong ascii

2024-11-10 18:26 UTC, thiennk581 commented on N24DCCN162/bai_1.cpp
> +        if(islower(c)){
> dạ điều kiện là phải là các kí tự chữ thường từ 97 đến 122 trong ascii

oke hiểu bản chất thì cho xài hàm. Nếu mới học thì hạn chế xài còn biết nhiều làm nhiều rồi thì ko sao

2024-11-11 02:02 UTC, thiennk581 requested changes
Em đã commit gì lên đâu mà request nhỉ
Nhớ nhấn Merge pull request của bài tập 3 đi nha

2024-11-11 02:03 UTC, yunttan commented
Dạ a

On Mon, 11 Nov 2024 at 09:03 Nguyen Khanh Thien ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Em đã commit gì lên đâu mà request nhỉ
> Nhớ nhấn Merge pull request của bài tập 3 đi nha
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/itmc-ptit/itmc-cpp-class-2024/pull/78#pullrequestreview-2425975853>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKGLFHSAYVXMBTGRHVEAQET2AAF53AVCNFSM6AAAAABRP4VKT6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRVHE3TKOBVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-11 09:50 UTC, closed without merging

2024-11-11 09:59 UTC, thiennk581 commented
sao xoá branch luôn ròi e

2024-11-11 10:49 UTC, yunttan commented
a ơi e up lại bài sửa sang cái branch khác nha a