em nop bt buoi 4 a
itmc-ptit/itmc-cpp-class-2024 pull request #86
Opened 2024-11-11 13:39 UTC by lenguyen144

2024-11-11 16:34 UTC, thiennk581 requested changes
bạn 090 xem lại bài 1
bạn 144 xem lại bài 8

2024-11-11 16:34 UTC, thiennk581 commented on N24DCCN144/buoi_4/bt_8.cpp
> +    if ( (a + b < c) || (a + c < b) || (b + c < a) )
điều kiện tam giác: tổng 2 cạnh phải lớn hơn cạnh còn lại
giờ anh cho a = 1, b = 2, c = 3, theo điều kiện if dòng 14 của em thì câu if này sẽ ra false cho cả 3 điều kiện
nhưng a + b = 1 + 2 có lớn hơn 3 không? hay em vẽ đc tam giác có 3 cạnh là 1, 2, 3 đi anh cho qua:)

2024-11-12 11:56 UTC, lenguyen144 commented on N24DCCN144/buoi_4/bt_8.cpp
> +    if ( (a + b < c) || (a + c < b) || (b + c < a) )
:{{

2024-11-12 12:18 UTC, lenguyen144 commented on N24DCCN144/buoi_4/bt_8.cpp
> +    if ( (a + b < c) || (a + c < b) || (b + c < a) )
em đã sửa bài ạ

2024-11-12 13:37 UTC, thiennk581 approved these changes
oke, nhớ nhấn **Merge pull request** nha

2024-11-13 02:28 UTC, merged