N24dece089/buoi4
itmc-ptit/itmc-cpp-class-2024 pull request #89
Opened 2024-11-12 01:27 UTC by samho-hacker

2024-11-12 04:17 UTC, thiennk581 requested changes
thiếu điều kiện câu 6, 7, 9
sai câu 8

2024-11-12 04:17 UTC, thiennk581 commented on N24DECE089/buoi4/cau11.cpp
> +    if ( a < 100 ) { if ( b == 0  )  { hdv(a) ;}  else if ( a == 0 )  {cout << " khong " ;}  else  { hc(b) ; hdv(c);  } }
biết dùng khối lệnh rõ ràng cho mỗi if else
(học tư tưởng viết hết trong 1 dòng ở đâu đây?:) )

2024-11-12 04:17 UTC, thiennk581 commented on N24DECE089/buoi4/cau6.cpp
> +   else { cout << " day khong phai la nam nhuan " ; }
thiếu 1 điều kiện nữa
vd: năm 2000 là năm nhuận nhưng bài của e ra sai

2024-11-12 04:17 UTC, thiennk581 commented on N24DECE089/buoi4/cau7.cpp
> +   else if ( b = 0 ) { x = 0 ; cout << x ; }
nếu anh nhập a = 0, b = 0 thì sao
pt bậc nhất sẽ có 3 trường hợp: có nghiệm, vô nghiệm, vô số nghiệm

2024-11-12 04:17 UTC, thiennk581 commented on N24DECE089/buoi4/cau8.cpp
> +   else if ( a == b == c ) { cout << " day la tam giac deu "; }
1. biểu thức sẽ có sự tham gia của 2 toán hạng và 1 toán tử
nếu em viết như này máy nó sẽ hiểu là ( (a == b) == c )
(a == b) thì nó sẽ trả về true/false tương ứng là 1/0
vậy lúc này biểu thức sẽ trở thành ( 1 == c) hoặc (0 == c) vậy  còn đúng nữa ko?
cách viết của em là viết trên giấy, khi thể hiện lên code sẽ phải ghi rõ ràng ra: ` (a == b) && (b == c) `

2. phải kiểm tra tam giác đều trước tam giác cân
giờ anh nhập 3 3 3 thì đụng cái điều kiện tam giác đều trước và nó thoả mãn => kết luận tam giác cân, nhưng đúng ra lại là tam giác đều

2024-11-12 04:17 UTC, thiennk581 commented on N24DECE089/buoi4/cau8.cpp
> +   else if ( a == 0 || b == 0 || c == 0 || a + b < c || b + c < a || a + c < b  ) { cout << " day khong phai la mot tam giac " ; }
em nên xét coi có phải tam giác hay không đầu tiên, nếu thoả mãn thì kiểm tra coi tam giác đó là gì
Điều kiện tam giác: tổng 2 cạnh bất kì lớn hơn cạnh còn lại
nếu anh nhập 1, 2, 3 thì khi đưa vào câu if này nó sẽ trả về false và kết luận đây là 1 tam giác thường
nhưng theo điều kiện gốc ở trên thì 1 + 2 có lớn hơn 3 không?

2024-11-12 04:17 UTC, thiennk581 commented on N24DECE089/buoi4/cau9.cpp
> +   else if (a == 0 && c == 0 ) { x = 0 ; cout << "phuong trinh co nghiem la : " << x ; }
như bài 7, thiếu trường hợp vô số nghiệm

2024-11-14 07:15 UTC, samho-hacker commented
em có sửa lại hết r đấy ạ anh xem lại giúp em

2024-11-14 10:38 UTC, thiennk581 approved these changes
đúng hết rồi nha, có thể nhấn **merge pull request** đc rồi
xem thử vài góp ý nha
_mã dece là ngành gì vậy em:v_

2024-11-14 10:38 UTC, thiennk581 commented on N24DECE089/buoi4/cau6.cpp
> +   if( ( a % 4 == 0 && a % 100 != 0 ) || ( a % 4 == 0 && a % 100 == 0 && a % 400 == 0 ) ) { cout << " day la nam nhuan " ; }
nếu a chia hết cho 400 thì a sẽ chia hết cho cả 4 và 100 nên 2 điều kiện chia hết cho 4,100 bị thừa, chia hết cho 400 là đủ rồi nha e (ko sai nên ko cần sửa đâu, nhắc thôi)

2024-11-14 10:38 UTC, thiennk581 commented on N24DECE089/buoi4/cau7.cpp
> +   else if ( b == 0 ) { x = 0 ; cout << " phuong trinh co mot nghiem la : " <<  x ; }
chỗ này có thể viết lại như sau:
```
if (a == 0) {
    if (b == 0) 
        {   cout << "Vo so nghiem";  }
    else 
        {  cout << "Vo nghiem";  }
}
else 
    {   cout << "x = " << -b/a;  }
```
ít điều kiện và dễ quản lý hơn hẳn. Em để ý thấy biến a xuất hiện 3 lần trong 3 câu if không, hãy gắng gộp nó lại đỡ lặp nhiều

2024-11-14 10:38 UTC, thiennk581 commented on N24DECE089/buoi4/cau9.cpp
> +                        if ( delta > 0 ) { x1 = (-b + sqrt(delta))/(2*a ); x2 = (-b - sqrt(delta))/(2*a ) ; cout << " phuong trinh co hai nghiem phan biet " << x1 << "va" << x2 ; }
em đếm xem thằng a lặp bao nhiêu lần?:)
giờ a = 0 thì xử lý phương trình bậc nhất bx + c = 0, ngược lại thì xử lý phương trình bậc 2 ax^2 + bx + c = 0
em thử dùng góp ý của anh ở bài 7 để dòng if bớt điều kiện lại xem.

2024-11-15 02:53 UTC, merged